import React, { Component } from 'react'
import Navbar from './Navbar'
import axios from 'axios'

class Singlesector extends Component {
    state = {
        sectorData: null,
        value: null,
        selected: false
    }

    componentDidMount() {
        this.getData()
    }

    componentWillUpdate() {
        const { selected, value } = this.state

        if (selected && value) {
            this.setState({
                selected: false
            })
        }

    }


    getData = async () => {
        let res = await axios.get('https://smartcity-parking-api.herokuapp.com/sectors')
        const sectors = await res.data.data

        const sectorsLinks = await Promise.all(sectors.map(sector => axios.get(sector.self_links.detail)))

        this.setState({
            sectorData: sectorsLinks
        })
    }

    handleChange = ({ target }) => {
        this.setState({
            value: target.value,

        })
    }


    handleSubmit = (e) => {
        e.preventDefault()
        if (this.state.value) {
            this.setState({
                selected: true
            })
        }
    }

    render() {
        const { sectorData, value, selected } = this.state
        let content, loadedContent

        if (sectorData != null) {
            content =
                <div className="field">
                    <label className="label">Subject</label>
                    <div className="field is-grouped">
                        <div className="control">
                            <div className="select is-large">
                                <select onChange={this.handleChange}>
                                    <option hidden disabled selected value> Select a sector </option>
                                    {sectorData.map((sector, i) => {
                                        return <option value={i}>Sector id: {i}</option>
                                    })}
                                </select>
                            </div>
                        </div>
                        <form onSubmit={this.handleSubmit}>
                            <button type='submit' className="button is-link is-large">Select this sector</button>
                        </form>

                    </div>
                </div>

        } else {
            content = <p>Wait till content is loaded</p>
        }

        if (selected) {

            loadedContent = <div className='content'>
                <h2>{sectorData[value].data.data.sector_data.occupance_percentage}</h2>
                <div className="columns">
                    <div className="column">                        
                        <article class="message is-primary">
                            <div class="message-header">
                                <p>Parking data generated by cluster {sectorData[value].data.data.sector_data.sector_id}</p>
                            </div>
                            <div class="message-body">
                            <div className='list'>
                                <span className="list-item">Current occupation percentage: <span className="has-text-weight-bold"> {sectorData[value].data.data.sector_data.occupance_percentage * 100}</span></span>
                                <span className="list-item">slgdksgd</span>
                                <span className="list-item">slgdksgd</span>
                                <span className="list-item">slgdksgd</span>
                                <span className="list-item">slgdksgd</span>

                               
                            </div>
                            </div>
                        </article>
                    </div>
                    <div className="column">
                        Second column
                    </div>


                </div>
            </div>
        }
        return <div className='page'>
            <Navbar />
            <div className="container">
                <div className="content">
                    <section className="section">
                        <h1 className="title is-size-1">Single sector</h1>
                        {content}

                        <hr></hr>

                        {loadedContent}
                    </section>
                </div>
            </div>
        </div>




    }
}

export default Singlesector